[package]
name = "class_list_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.27"
syn = { version = "2.0.15", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
